实验背景:双节点组成集群，节点为node1和node2
索引名称:keyword
索引关键字段:id,name

场景1:
a)node1和node2均为活动状态
b)任意选择一节点进行数据录入
c)停止node2
d)对node1进行增删改操作
e)启动node2，待集群状态为健康(green)。
f)停止node1
g)查询node2数据
结果:数据同步

场景2:
a)node1和node2均为活动状态
b)任意选择一节点进行数据录入
c)停止node1
d)node2删除索引结构(注不是索引数据)
f)启动node1
结果:node2上面删掉的索引结构包括索引数据都会根据node1的数据原封不懂同步回node2上面

场景3:
a)node1和node2均为活动状态
b)任意选择一节点进行数据录入
c)停止node2
d)对node1进行增删该操作
    增加:id=k009数据
    修改:id=k008的数据,将name修改为"空调被1"
    删除:id=k007
e)停止node1
f)启动node2
g)对node2进行增删改操作
    增加:id=k010数据
    修改:id=k008的数据,将name修改为"空调被2"
    删除:id=k006
h)停止node2
i)先启动node1，后启动node2
结果:集群数据以先启动的node1数据为准，因为node1先启动，被认为是主节点